# Interface WiFi
interface=wlp3s0

# Plage DHCP
dhcp-range=192.168.99.50,192.168.99.150,12h

# Fichier de leases
dhcp-leasefile=/var/lib/dnsmasq/dhcp.leases

# DNS
server=8.8.8.8
server=8.8.4.4

# Logs
log-queries
log-dhcp
log-facility=/var/log/dnsmasq-queries.log
